#!/bin/sh

# This is the brainfart install script
#
# <p> Are you looking at this in your web browser? <p>
 
# curl https://eranws.github.io/brainfart/install/ | sh

# init git ?
curl https://eranws.github.io/brainfart/fart > fart
chmod +x ./fart

echo Download successful.
./fart "- I am farting right now"
